name: Clean up closed PR

on:
  pull_request:
    types: [closed]
  branches:
    - main

jobs:
  clean-up:
    # only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find Proposals
        id: changed-files
        uses: tj-actions/changed-files@32d6fb28f082f273420574e9de0a30be993bba58
        with:
          separator: " "

      - name: Remove drafts that are not in main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
        run: /bin/bash .github/scripts/deploy_cleanup.sh
